std_msgs/Header header

# ESR status2
uint8       rolling_count2
uint8       maximum_tracks_ack
bool        raw_data_mode
bool        xcvr_operational # radiating
bool        internal_error
bool        range_perf_error
bool        overheat_error
uint16      steer_angle_ack
int8        temperature
uint8       grouping_mode
float32     veh_spd_comp_factor
float32     yaw_rate_bias
string      sw_version_dsp
